kind: role
version: v8
metadata:
  name: example-reviewer
spec:
  allow:
    review_requests:
      roles: ['example-prodops']
---
kind: role
version: v8
metadata:
  name: example-devops
spec:
  allow:
    db_names:
    - '{{internal.db_names}}'
    - 'sportsdb_sample'
    db_labels:
      'env': 'dev'
    db_users:
    - '{{internal.db_names}}'
    - postgres      
    app_labels:
      'env': 'dev'
    node_labels:
      env: dev
    logins:
    - '{{internal.logins}}'
    - ubuntu
    - '{{email.local(external.email)}}'
    - '{{email.local(external.username)}}'
    request:
      roles: ['example-prodops']
      search_as_roles: ['example-prodops']
  options:
    create_host_user_default_shell: bash
    create_host_user_mode: keep
---
kind: role
version: v8
metadata:
  name: example-prodops
spec:
  allow:
    logins: ['ubuntu', '{{email.local(external.email)}}','{{email.local(external.username)}}', '{{internal.logins}}']
    app_labels:
      env: prod
    node_labels:
      'env': 'prod'
    db_names:
    - '{{internal.db_names}}'
    - 'sportsdb_sample'
    db_users:
    - '{{internal.db_names}}'
    - postgres
    db_labels:
      'env': 'prod'
  options:
    create_host_user_default_shell: bash
    create_host_user_mode: keep
---
kind: role
version: v5
metadata:
  name: example-editor
spec:
  allow:
    impersonate:
      roles:
      - Db
      users:
      - Db
    rules:
    - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
---
kind: access_monitoring_rule
metadata:
  name: prod-access
spec:
  automatic_review:
    decision: APPROVED
    integration: builtin
  condition: |-
    contains_all(set("example-prodops"), access_request.spec.roles) &&
    access_request.spec.resource_labels_intersection["env"].contains("prod")
  desired_state: reviewed
  subjects:
  - access_request
version: v1
