#!/bin/bash

# no need to check roles if user is root
if [[ "${TELEPORT_LOGIN}" == "root" ]]; then
  exit 0
fi

COMMENT="User ${TELEPORT_USERNAME} with roles ${TELEPORT_ROLES} created by Teleport."
id -u "${TELEPORT_LOGIN}" &>/dev/null  || /usr/sbin/useradd -m -c "${COMMENT}" "${TELEPORT_LOGIN}" -s /bin/bash 2> /tmp/pam.error

exit 0
